"""owner and ip

Revision ID: 1497a9ee71e5
Revises: 29af0d2671af
Create Date: 2019-03-29 17:47:28.550108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1497a9ee71e5'
down_revision = '29af0d2671af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('clout', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_description'), 'ip', ['description'], unique=True)
    op.create_index(op.f('ix_ip_name'), 'ip', ['name'], unique=True)
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('clout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_name'), 'owner', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_name'), table_name='owner')
    op.drop_table('owner')
    op.drop_index(op.f('ix_ip_name'), table_name='ip')
    op.drop_index(op.f('ix_ip_description'), table_name='ip')
    op.drop_table('ip')
    # ### end Alembic commands ###
