"""note table 2

Revision ID: 29af0d2671af
Revises: b1123539d708
Create Date: 2019-03-26 18:24:39.152360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29af0d2671af'
down_revision = 'b1123539d708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=280), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_timestamp'), 'note', ['timestamp'], unique=False)
    op.drop_index('ix_notes_timestamp', table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=280), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_timestamp', 'notes', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_note_timestamp'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
