"""owner relationship

Revision ID: 8fec1923866f
Revises: 1497a9ee71e5
Create Date: 2019-03-29 17:59:28.557158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fec1923866f'
down_revision = '1497a9ee71e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip', type_='foreignkey')
    op.drop_column('ip', 'owner_id')
    # ### end Alembic commands ###
