"""creation

Revision ID: a3a03b3142a7
Revises: 47e19f434629
Create Date: 2019-04-19 18:38:15.754966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a03b3142a7'
down_revision = '47e19f434629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('ip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ip_id'], ['ip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('ip') as batch_op:
    #     batch_op.drop_column('owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.drop_table('creation')
    # ### end Alembic commands ###
